import fs from "fs";
import path from "path";
import crypto from "crypto";

export function ensureEncryptionKey() {
    // If the key already exists and is valid, do nothing
    if (process.env.ENCRYPTION_KEY) {
        return;
    }

    console.log("No ENCRYPTION_KEY found in environment. Generating a new 32-byte key...");

    // Generate a secure 32-byte key (64 hex characters)
    const newKey = crypto.randomBytes(32).toString("hex");

    // Path to the .env file
    const envPath = path.resolve(process.cwd(), ".env");

    try {
        // Append it to the .env file so it persists across server restarts
        fs.appendFileSync(envPath, `\n# Auto-generated by backend on startup\nENCRYPTION_KEY=${newKey}\n`);
        console.log("Successfully generated and saved ENCRYPTION_KEY to .env file.");

        // Make it immediately available to the current running process
        process.env.ENCRYPTION_KEY = newKey;
    } catch (e) {
        console.error("Failed to write ENCRYPTION_KEY to .env file:", e);
        // Fallback: just keep it in memory (warning: will reset on restart)
        process.env.ENCRYPTION_KEY = newKey;
    }
}
